version: "3.8"

services:
  backend:
    build:
      context: .
      target: base
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: ["npm", "run", "dev"]
    depends_on:
      - database
  database:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - every_io_database_volume:/var/lib/postgresql/data
volumes:
  every_io_database_volume:
